apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz
  mysql-database: ZW50cnl0cmFja2VyX2Ri
  mysql-user: YXBwX3VzZXI=
  mysql-password: YXBwX3Bhc3N3b3Jk
