name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run the app in background
        run: |
          nohup python3 app.py &
          sleep 5

      - name: Unit test - verify app responds
        run: |
          curl http://localhost:5000 | grep "expected output"

      - name: Build Docker image
        run: docker build -t naamaf280/cowsay-app:latest .

      - name: Run E2E test (docker-compose)
        run: |
          docker-compose up -d
          sleep 5
          curl http://localhost:5000 | grep "expected output"
          docker-compose down

